name: build

on:
  push:
    branches: [ OwO ]
  pull_request:
    branches: [ OwO ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
    - uses: actions/checkout@v2
    - name: install typescript
      run: pacman --noconfirm -Sy typescript
    - name: compile
      run: tsc
